{% set name = "Flask-WTF" %}
{% set version = "1.1.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/Flask-WTF-{{ version }}.tar.gz
  sha256: 10fd267a41b6dee4f433ec8d6507d4cce4f1d71700280cf654a7cdbae6408d47

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . --no-deps -vv

requirements:
  host:
    - python >=3.7
    - pip

  run:
    - python >=3.7
    - flask
    - itsdangerous
    - wtforms

test:
  requires:
    - pip
  imports:
    - flask_wtf
    - flask_wtf.recaptcha
  commands:
    - pip check

about:
  home: https://github.com/lepture/flask-wtf
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE.rst
  summary: Simple integration of Flask and WTForms
  dev_url: https://github.com/lepture/flask-wtf
  doc_url: https://flask-wtf.readthedocs.io/en/stable/

extra:
  recipe-maintainers:
    - pmlandwehr
    - xylar
