{% set name = "Flask-WTF" %}
{% set version = "0.15.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: ff177185f891302dc253437fe63081e7a46a4e99aca61dfe086fb23e54fff2dc

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . --no-deps -vv

requirements:
  host:
    - pip
    - python >=3.6

  run:
    - python >=3.6
    - flask
    - itsdangerous
    - wtforms

test:
  requires:
    - pip
  imports:
    - flask_wtf
    - flask_wtf.recaptcha
  commands:
    - pip check

about:
  home: https://github.com/lepture/flask-wtf
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE
  summary: Simple integration of Flask and WTForms
  dev_url: https://github.com/lepture/flask-wtf
  doc_url: https://flask-wtf.readthedocs.io/en/stable/

extra:
  recipe-maintainers:
    - pmlandwehr
    - xylar
