travis:
  secure:
    BINSTAR_TOKEN: RXX9VY8hpGJ6wZciVTamRUlaeKv+JfGdjytlo2JNNkASuADYMxZ+N0hvgPvrVQZBgcTGYfTTMEbnsoqp61mDbf/FM7CsYnCox/ws8F6pB51EzAaKsUpZ2eE0n6vlsATbfz+KSRmdcrja0+/1qruzbNRGlngO+BoVQaWGj7XB8HkHXaclnMhLoy8uHox+a/L/yJILu0vc7jlvOAM3vGRrq6KK7WCcre1SxUolcQ8dWdBCvaxdNJiJD6vW82N1K251hZifR9Tr1RCev9rHPGTnTqQJOo8/jU1eMUR6c3KaoUOvpzys9/MaQ2U9YupWboc33dO2+ubRBMqaGPpfjVYUbQyLkfvkXgzvN9kZ2UMMnK08E2dpqo8643oL5DQGnBXUnwJ0TnQd3BIQWxmtPAySUgH1zpMNDQYMhQ2Xff6SrfbJzMAhHAOiRfCllpCvMYwcGNImd+7crhxbm9FUhPpxknDDLCNrt0oxXao/LuWkHReou/4qSXFKwDNJv6+Gd6xUsTOf+UWfdUAz3L9curtfEpOz3xsoIGtHayxS//sWHk3wN2AZXRfdN69D4Ib/DWp4Zv/pI+REsdONkpezB7vFBO/7hJ2d01rl8BL6FO/6hnLcsvrqYymMBMwVhhxrmdUCcddBwIGPAOoKis9n7wxRM4OjpXARM1DX/3hxTlnkdsY=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
